---
- hosts: controller
  become: True
  
  tasks: 
    - name: Create a 2048-bit SSH key for user vagrant in ~vagrant/.ssh/id_rsa
      user:
        name: vagrant
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Copy private key to other hosts to make password less login
      command: ssh-copy-id -i ~/.ssh/id_rsa {{ item }}
      with_items:
       - ubu
       - cent





- hosts: India
  remote_user: vagrant
  become: True
  
  tasks:
   - name: copy /etc/hosts file to other servers
     copy: src=/etc/hosts dest=/etc/hosts

     